server:
  port: 8080

app:
  api-prefix: /gateway/v1

spring:
  application.name: gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2