server:
  port: 8083
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: ${URI_NEO4J}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
cloudinary:
  cloud_name: dis2ybh5i
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECREST}